# https://mattvsts.github.io/2020/01/07/create-a-build-matrix-with-azure-pipelines/

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '4gcc/test-fio.sh'

jobs:
- job: FIO_TEST_MATRIX
  pool:
    vmImage: 'ubuntu-20.04'
  timeoutInMinutes: 360
  steps:

  - script: |
      set -e
      set -u
      script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
      Say --Reset-Stopwatch

      Say "Registering qemu user static"
      sudo apt-get install qemu-user-static -qq -y >/dev/null
      docker run --rm --privileged multiarch/qemu-user-static:register --reset >/dev/null 2>&1 
      cd 4gcc

      source build-gcc-utilities.sh
      Say "CPU: [$(get_cpu_name)]"
      source test-fio-matrix.sh
    displayName: 'FIO TEST MATRIX'
        PASSWORD: $(SECRET_PASSWORD)
        LOGIN: $(SECRET_LOGIN)
        SSH_HOST_AND_PATH: $(SECRET_SSH_HOST_AND_PATH)

  - script: |
      Say "System Statisctics"
      Show-System-Stat
      Say "Free Size"
      sudo df -h -T
      Say "Containers"
      docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Status}}"

      set -e
      cd 4gcc
      source build-gcc-utilities.sh
      Say --Display-As=Error "Not Implemented"

    condition: succeededOrFailed()
    displayName: 'Grab Artifacts'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'ALL @ Publish'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'

